# Generated by Django 3.0.3 on 2020-03-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('title', models.CharField(choices=[('Research', 'Research'), ('Editor', 'Editor'), ('Logistics', 'Logistics'), ('Moderator', 'Moderator'), ('Graphics', 'Graphics'), ('Video', 'Video')], max_length=150, verbose_name='Title')),
                ('team', models.CharField(choices=[('Tarim Talks Team', 'Tarim Talks Team'), ('Tarim Stars Team', 'Tarim Stars Team'), ('Uyghur Exchange Team', 'Uyghur Exchange Team')], max_length=150, verbose_name='Team')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='contributors/', verbose_name='Image')),
                ('sm_instagram', models.CharField(max_length=150, verbose_name='Instagram')),
                ('sm_twitter', models.CharField(max_length=150, verbose_name='Twitter')),
                ('sm_linkedin', models.CharField(max_length=150, verbose_name='Linkedin')),
            ],
            options={
                'verbose_name': 'Contributors',
                'verbose_name_plural': 'Contributors',
            },
        ),
    ]
